### ISSUE TITLE
Authenticator

### ISSUE THREAD

**Issue by claudiobolivar** [EDCD/EDMarketConnector#2302] opened 2024-09-28 13:34 UTC
Good morning, I speak Spanish, excuse my English, but since the last update I can't connect through the authenticator, the screen stays black, it only happens with this application, what could be the problem?

**Comment by Ar9yria** [comment] 2024-09-28 14:46
I'm having similar problems, I think. EDMC opens Frontier log-in page. I enter my username and password - and nothing happens.  Frontier log-in IS working for other functions (eg Frontier Gamestore and Forums). I've tried uninstalling and reinstalling EDMC but with the same result.

**Comment by Ar9yria** [comment] 2024-09-28 20:54
I've solved the problem by rolling back EDMC to the previous version (5.11.3). So seems there is some issue with 5.12.0

**Comment by Tarmstrong7** [comment] 2024-09-28 21:36
I'm also this problem, EDMC does not prompt me with the Frontier log-in page. I followed troubleshooting and made sure it could see my journal files and was not in cloud. I also uninstalled and installed a previous version to no avail. Tried once more after updating through the app and still nothing.

**Comment by Tarmstrong7** [comment] 2024-09-28 23:00
Solved with following steps: 
- Use [release 5.11.3](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.11.3) although I'm not sure if this is required or not
- Launching the game AND entering solo play (loading the game is never stated anywhere even in troubleshooting)
- Launch EDMC by navigating "C:\Program Files (x86)\EDMarketConnector" and running "EDMarketConnector - localserver-auth.bat" (EDMC must be closed)
- If you get an error 500 when attempting to authenticate, select change account and login with Steam

**Comment by Rixxan** [comment] 2024-09-29 13:34
Hello!

Thank you for reporting an issue. 

Please check if the solution from Tarmstrong7 above fixes the issue. 

If not, please provide your program log files so I can review them.

**Comment by claudiobolivar** [comment] 2024-09-29 13:37
> Solved with following steps:
> 
> * Use [release 5.11.3](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.11.3) although I'm not sure if this is required or not
> * Launching the game AND entering solo play (loading the game is never stated anywhere even in troubleshooting)
> * Launch EDMC by navigating "C:\Program Files (x86)\EDMarketConnector" and running "EDMarketConnector - localserver-auth.bat" (EDMC must be closed)
> * If you get an error 500 when attempting to authenticate, select change account and login with Steam

Correct this was the solution

**Comment by Rixxan** [comment] 2024-09-29 15:16
Closing this report as duplicate, continuing to investigate root cause in #2303

**Closed by Rixxan** 2024-09-29 15:16 UTC
Labels: bug, unconfirmed
