### ISSUE TITLE
Better management of mouse and Focus when "Always on Top" is enabled

### ISSUE THREAD

**Issue by parduz** [EDCD/EDMarketConnector#1199] opened 2021-07-17 09:05 UTC
I use the SpanshRouter plugin, and i like to have the EDMC Form transparent over the game screen. But when the mouse goes over it (maybe i'm scanning the system, so my "game mouse" is not where the "Windows system mouse" is) EDMC grabs the focus and activates itself.

What i'd like is 

- an option that defines a keyboard key that need to be pressed in combination to the mouse presence over the window to make it activates, so that if the key is unpressed (but defined) the Form never grab the focus.
- an options for a key that hides the window entirely, either by toggle or "while pressed" logic, so i can hide it while doing certain actions in the game.

_(sorry for my poor english, i'm italian)_

**Comment by Athanasius** [comment] 2021-07-17 10:11
Duplicate of #889

**Closed by Athanasius** 2021-07-17 10:11 UTC
Labels: duplicate, enhancement
