### ISSUE TITLE
Upload/output settings re-enable themselves if user has disabled all upload/output settings

### ISSUE THREAD

**Issue by Sajime** [EDCD/EDMarketConnector#407] opened 2019-03-02 05:42 UTC
Due to the logic in these lines: https://github.com/Marginal/EDMarketConnector/blob/04563cadaefca0213faf8a133dc3aeb12b5df50c/prefs.py#L104
https://github.com/Marginal/EDMarketConnector/blob/1dc6d04954c7b9b0bad537510700299db50611c6/plugins/eddn.py#L350
Ship loadout output, and EDDN sending options, will attempt to restore their default (enabled) state if `output` is set to `0`, i.e. all file outputs and EDDN uploads have been disabled. The unexpected re-enabling of these settings may give the impression that the configuration failed to "stick" when the user has explicitly disabled them previously (e.g., if they use another tool for EDDN upload).

**Comment by Athanasius** [comment] 2020-06-20 09:28
I'll try to address this in the next few days ready for the pending final python 2.7-based release.

**Comment by Athanasius** [comment] 2020-06-29 11:39
OK, I've figured out how to reproduce this.  The key is that OUT_MKT_MANUAL is tied to Output > "Automatically update on docking", and because of the wording it's inverted.  So OUT_MKT_MANUAL gets *set* when you have the option UNticked, and vice versa.

1. Go into Settings.  On the EDDN tab ensure everything is UNticked.
1. On the Output tab ensure at least one of the top three options is ticked so that you can access the "Automatically update on docking" option.
1. Tick the "Automatically update on docking" option.
1. Now untick all the other options above it.
1. Click 'OK' to close Settings and save to Registry

Check Registry, the 'output' value is now 0x0.

But, if you now open Settings again. You'll have all the following seleted:

* Output > Ship loadout
* Output > Automatically update on docking
* EDDN > Send station data to the Elite Dangerous Data Network
* EDDN > Send system and scan data to the Elite Dangerous Data Network

If you have at least one other 'output' option active then this won't happen as the overall value of the registry key won't be 0x0, so will be 'true' and you won't get the defaults set.

**Comment by Athanasius** [comment] 2020-06-29 14:49
This should be fixed in the next release (likely a pre-release 3.99.0.0 for last minute testing of switch to Python 3.7).

**Closed by Athanasius** 2020-06-29 14:49 UTC
Labels: bug
