### ISSUE TITLE
Styling issues with tkinter 8.6.14

### ISSUE THREAD

**Issue by der-eismann** [EDCD/EDMarketConnector#2235] opened 2024-05-13 18:26 UTC
- Version: 5.10.6
 - Game Version: Odyssey
 - OS: Linux Fedora 40
 - OS Locale: English
 - If applicable: Browser [e.g. chrome, safari]

**Describe the bug**
Recently [tkinter 8.6.14](https://sourceforge.net/projects/tcl/files/Tcl/8.6.14/) was released. I tried updating it for the Flatpak version of EDMC (see https://github.com/flathub/io.edcd.EDMarketConnector/pull/42), however some parts of the styling was off. I don't have any idea how this works and I don't know when this version would be included in "normal" Python distributions, but it might make sense to investigate this. Maybe you can give me a hint where to start? Or is it obsolete because of #2116?
In this case URLs are just way larger and also hovering Ship, System & Station on the main screen will cause the layout to change since the font size increases when being hovered.

**To Reproduce**
1. Run with tkinter 8.6.14

**Expected behavior**
Consistent style as was before

**Screenshots**

tkinter 8.6.13:
![Bildschirmfoto vom 2024-05-13 20-15-12](https://github.com/EDCD/EDMarketConnector/assets/10406217/1e68b42e-6a47-45cf-a2fc-8a1f3bbc892c)

tkinter 8.6.14:
![Bildschirmfoto vom 2024-05-13 20-16-11](https://github.com/EDCD/EDMarketConnector/assets/10406217/8afa9ef5-5787-4e7b-841b-15eb648de309)

**Comment by der-eismann** [comment] 2024-05-13 21:25
Opened this issue over at the tcl/tk repo: https://core.tcl-lang.org/tk/tktview/8162e9b7a90465f0b2a761c9515dfbc45d4b7e9f
Maybe it's a Linux issue, maybe it's just because of my 200% display scaling, let's see.

**Comment by dvdmuckle** [comment] 2024-05-14 00:49
For what it's worth, this doesn't happen on my machine, and I'm not using any scaling. I can test on my laptop that does have 200% scaling, but it sounds like that might be the cause.

**Comment by Rixxan** [comment] 2024-05-14 21:39
Given this is likely an upstream issue with TCL/TK, marking as such. Will monitor until TCL/TK either kicks it back or fixes it.

**Comment by der-eismann** [comment] 2024-05-14 21:41
> For what it's worth, this doesn't happen on my machine, and I'm not using any scaling. I can test on my laptop that does have 200% scaling, but it sounds like that might be the cause.

Did you test [this build](https://github.com/flathub/io.edcd.EDMarketConnector/pull/42#issuecomment-2106383330)? Would be great if you could test it on another device :slightly_smiling_face: 
I guess we could implement a workaround, but let's see what TCL/TK does first.

**Comment by Rixxan** [comment] 2024-05-30 23:11
@der-eismann The TCL team seems to have closed the ticket - is the latest version of TCL/TK working?

**Comment by Rixxan** [comment] 2024-09-24 23:56
@dvdmuckle @der-eismann Does the latest version fix it? It looks like they pushed .15

**Comment by dvdmuckle** [comment] 2024-09-25 03:04
So I just tested EDMC 5.12.0 with 8.6.15 of tkinter, and while I never had this particular error before, everything seems to be functional. Here's the PR with those changes for the Flatpak https://github.com/flathub/io.edcd.EDMarketConnector/pull/55

**Comment by dvdmuckle** [comment] 2024-09-25 22:18
For the sake of additional testing I'm going to revert the tkinter changes in the aforementioned PR and put those into a new branch to let @der-eismann test those as I can replicate the issue in this PR.

**Comment by Rixxan** [comment] 2024-12-19 21:27
@dvdmuckle @der-eismann Given that this error is resolved, closing this ticket. If the situation replicates, please feel free to reopen.

**Closed by Rixxan** 2024-12-19 21:27 UTC
Labels: bug, upstream, ui
