### ISSUE TITLE
ED Market Connector stops astronomical discoveries being logged in the Codex

### ISSUE THREAD

**Issue by MiffyMcMifferson** [EDCD/EDMarketConnector#2304] opened 2024-09-29 04:23 UTC
[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: 5.12.0+cc6e200
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: English
 - If applicable: 

**Describe the bug**

[//]: When running it seems the ED Market Connector stops new astronomical discoveries from being logged by the in game Codex. I discovered a Wolf-Rayet and a B type SuperGiant but they did not appear as discovered in the Codex. When I ran the game without ED Market Connector running, I discovered an A type SuperGiant and this time the discovery was logged by the Codex.

**To Reproduce**
Run ED Market Connector, run game, make new astronomical discovery and check to see if that discovery is logged in the Codex.

**Expected behavior**

[//]: Codex should show all discoveries

**Comment by klightspeed** [comment] 2024-09-29 09:15
Did you happen to be near the edge of a galactic region? Refer https://issues.frontierstore.net/issue-detail/13286

**Comment by MiffyMcMifferson** [comment] 2024-09-29 11:23
Hi

No, Wolf Rayet system is HD 156327, can't remember/find the M type Giant system.  But both are well inside the Inner Orion Spur.

Thanks for your reply 🙂
________________________________

**Comment by Rixxan** [comment] 2024-09-29 13:33
This doesn't seem possible and is likely the combination of two unrelated events. 

EDMC cannot alter how your game registers discoveries and systems. The program only reads log files and doesn't alter the function or performance of the core game itself. 

If you are able to replicate this multiple times, let me know, but I don't think EDMC is in the root cause path for this one.

**Comment by klightspeed** [comment] 2024-09-29 22:31
I find it interesting that it seems that nobody has ever submitted a `CodexEntry` for `HD 156327` to EDDN.

Also of note is that `LAWD 26` has been coming through as `Codex_Ent_W_Type_Name` (despite being a white dwarf), suggesting that visiting that system might prevent the codex discovery of any plain Wolf-Rayet stars in the Inner Orion Spur.

**Comment by MiffyMcMifferson** [comment] 2024-09-29 22:40
Hi

Thanks for the info, I’ll have a look if I’ve visited LAWD 26. Definitely some bugs in there somewhere


Sent from my iPhone

On 30 Sep 2024, at 08:32, Ben Peddell ***@***.***> wrote:

﻿

I find it interesting that it seems that nobody has ever submitted a CodexEntry for HD 156327 to EDDN.

Also of note is that LAWD 26 has been coming through as Codex_Ent_W_Type_Name (despite being a white dwarf), suggesting that visiting that system might prevent the codex discovery of any plain Wolf-Rayet stars in the Inner Orion Spur.

**Comment by Rixxan** [comment] 2024-12-19 21:25
Closing as this does not appear to be related to EDMC. Please feel free to reopen if the error replicates and we can trace behavior to EDMC!

**Closed by Rixxan** 2024-12-19 21:25 UTC
Labels: bug, unconfirmed
