### ISSUE TITLE
App fails to start when Git binary is not present

### ISSUE THREAD

**Issue by der-eismann** [EDCD/EDMarketConnector#2125] opened 2023-12-30 10:16 UTC
**Please complete the following information:**
 - Version: 5.10.0
 - OS: Linux with Flatpak

**Describe the bug**
When testing https://github.com/flathub/io.edcd.EDMarketConnector/pull/32, I get the following error:
```
Traceback (most recent call last):
  File "/app/edmarketconnector/EDMarketConnector.py", line 61, in <module>
    import killswitch
  File "/app/edmarketconnector/killswitch.py", line 20, in <module>
    import config
  File "/app/edmarketconnector/config/__init__.py", line 149, in <module>
    user_agent = f'EDCD-{appname}-{appversion()}'
                                   ^^^^^^^^^^^^
  File "/app/edmarketconnector/config/__init__.py", line 141, in appversion
    shorthash = git_shorthash_from_head()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/edmarketconnector/config/__init__.py", line 95, in git_shorthash_from_head
    git_cmd = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

I guess this was introduced in #2084 when the exception was modified, but I'm not 100% sure. Now most people do have Git, but it shouldn't be a hard requirement, especially if there's a fallback to  the .gitversion file.
/cc @dvdmuckle

**To Reproduce**
1. Download .tar.gz archive
2. Uninstall Git
3. Try to run app

**Expected behavior**
App should start

**Comment by Rixxan** [comment] 2023-12-30 16:28
Confirmed and fix in testing. Looks like also handling a FileNotFound error here would fix.

**Comment by Rixxan** [comment] 2023-12-30 16:34
PR 2126 opened to fix. Will be included in 5.10.1 in early Jan.

**Comment by Rixxan** [comment] 2023-12-30 21:56
@der-eismann, can you possibly double-check for me that updating this line
https://github.com/EDCD/EDMarketConnector/blob/b0b9113e51d2f075618c635ce307963310221782/config/__init__.py#L102

to this

 https://github.com/EDCD/EDMarketConnector/blob/d333450bef6696f791b7fdbf47d321e4bf11b1ee/config/__init__.py#L102

Also resolves the issue on your flatpak tester? I'm testing it here but want to make sure there isn't another issue this is masking.

**Comment by der-eismann** [comment] 2023-12-30 23:04
Seems to work fine, I can run it after applying [this change](https://github.com/flathub/io.edcd.EDMarketConnector/pull/32/commits/e10e500d310878fe9d9ab7cbd8aa4689b59844f0) :+1: Will merge it now and remove it after 5.10.1 is out.

**Comment by Rixxan** [comment] 2023-12-31 00:17
Hmm. Possibly depending on how the logging is set up? I'd have to refresh myself on logging levels.

**Closed** 2024-01-04 00:58 UTC
Labels: bug, python, Staged
