### ISSUE TITLE
Ed Market Connector does nothing.

### ISSUE THREAD

**Issue by rbradh53** [EDCD/EDMarketConnector#2061] opened 2023-08-07 19:19 UTC
I've used ED Market Connector for 4 years with no problems. I had to do a clean Windows install because of a hardware problem.
Upgraded to Windows 11 when I did the install. Downloaded and installed ED Market Connector now it just sits there. Does not try to 
get authorization from Elite Dangerous, cannot enter commander credentials for Inara or EDSM.
Under the Configuration tab, I tried the default setting and tried pointing to the journals folder, but neither worked. Uninstalled and reinstalled several times to no effect.

5.9.3+16ffdff
Odyssey
Windows 11
English
Cannot find "EDMarketConnector.log"
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/12284304/EDMarketConnector-debug.log)

![ED_MarketConnector](https://github.com/EDCD/EDMarketConnector/assets/79338607/978800c9-294b-452c-807c-abed5e9a3e62)

![ED_MarketConnector1](https://github.com/EDCD/EDMarketConnector/assets/79338607/eccb7bba-01a7-4d8a-921a-a5002d370a6a)

**Comment by Rixxan** [comment] 2023-08-07 19:30
Looks like same issue as #2057. Should be fixed by #2060. Hoping to have a fix pushed out on Wednesday!

**Comment by rbradh53** [comment] 2023-08-07 19:33
> Looks like same issue as #2057. Should be fixed by #2060. Hoping to have a fix pushed out on Wednesday!

Thank you.

**Comment by chennin** [comment] 2023-08-07 19:55
you didn't mention whether you logged in to the game (into solo/open/pg) while EDMC was still running. That's the old solution to this problem. Have you tried that?

**Comment by Rixxan** [comment] 2023-08-07 19:59
The issue, if it's what I'm thinking it is, is caused by the EDMC:// protocol not being handled properly by Windows and Frontier's auth system. This is due to a preference to the registry "open" command instead of "ddeexec". This means the protocol handler doesn't actually get processed successfully which causes the program to not receive the auth codes. 

For some weird reason, the program interprets this as a journal lock issue, which doesn't make a lot of sense. Will need to add additional logging, I think. The current open PR (#2060) adds that preferred handler key. I think later versions of the program will deprecate this handler for the local-auth system which currently exists as the backup.

**Comment by Rixxan** [comment] 2023-08-08 19:20
Fixed in 5.9.4. Leaving #2060 open as a master ticket for this issue if there are any follow-up issues.

**Closed by Rixxan** 2023-08-08 19:20 UTC
Labels: bug, duplicate, unconfirmed
