### ISSUE TITLE
Feature: Add "open log file" in either configuration tab or help menu (or both)

### ISSUE THREAD

**Issue by mIRCon** [EDCD/EDMarketConnector#1037] opened 2021-05-08 11:16 UTC
**Describe the enhancement**

Add "open log file" in either configuration tab next to log level setting or help menu or just add both if you want.

**Expected behavior**

When clicked users can open log file directly without a need to go to %temp% and search for logs, especially when troubleshooting with authors in EDCD discord, not to mention quick and convenient way to find the log file from EDMC itself.

**Considered workarounds**

N/A

**Additional context**

Example:
![image](https://user-images.githubusercontent.com/40735411/117537150-7a66a280-afff-11eb-9675-ea70d7a60884.png)

**Comment by Athanasius** [comment] 2021-05-26 21:53
Dupe of #510

**Closed by Athanasius** 2021-05-26 21:53 UTC
Labels: enhancement
