### ISSUE TITLE
difficult to read, nearly unable to select something in settings on high res screen (4k)

### ISSUE THREAD

**Issue by FJRMaverick** [EDCD/EDMarketConnector#686] opened 2020-09-08 10:36 UTC
On high resolution screens (here 4k) the scaling does not fit the needs. The main screen is difficult to read, but even worse: it cannot be seen if a box is selected or not in the settings screens. As a workaround I change the High-DPI-Settings of the executable, but then it looks very blurry and in transparent mode the font looks ugly.

**Comment by Athanasius** [comment] 2020-09-08 10:43
Duplicate of #515

**Closed by Athanasius** 2020-09-08 10:43 UTC
Labels: bug, unconfirmed

**Comment by Athanasius** [comment] 2020-09-09 14:41
To be certain you see it, I'll repeat myself here:

Please try out the [Pre-Release 4.1.0-beta2](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.0-beta2) as it has a new UI Scaling option.  Pay attention to the changelog notes about how it does, and doesn't, work.
