### ISSUE TITLE
EDMC Not Showing "Station" after Update

### ISSUE THREAD

**Issue by cmdrredhouse** [EDCD/EDMarketConnector#616] opened 2020-07-20 17:56 UTC
Hello

I installed the EDMC and everything works fine, except, now, after an update to EDMC, the "Station" no longer shows. It does show if I go into File, Status, and Ships... there it does show my current Station, but on the main screen... no Station info. When I first installed this EDMC, worked fine and showed all info, including Station. Then, like literally a day later, there was an update that took out the Station on the main interface screen. Then there was another update maybe two days later but still, no Station information.

I am using the latest version, have tried with ED running and not, have hit Update 10000000 times, went through every setting... no luck. Just stopped working after that update.

![EDMC](https://user-images.githubusercontent.com/68560854/87969779-9f415780-ca77-11ea-9296-457a19993522.png)

![EDMC](https://user-images.githubusercontent.com/68560854/87970473-a7e65d80-ca78-11ea-9d55-f857d4f8e61e.png)

**Comment by Athanasius** [comment] 2020-07-20 18:17
What do you have set for station provider?  'File' > 'Settings' > 'Configuration' ... 'Preferred websites' > 'Station'.

**Comment by cmdrredhouse** [comment] 2020-07-20 18:26
HI. I have INARA.

![7-20-2020 11-25-26 AM](https://user-images.githubusercontent.com/68560854/87972508-db76b700-ca7b-11ea-94ca-e7d27bb609cd.png)

**Comment by cmdrredhouse** [comment] 2020-07-20 18:29
Hmm, I changed it and now it works. 

![7-20-2020 11-28-51 AM](https://user-images.githubusercontent.com/68560854/87972777-55a73b80-ca7c-11ea-81f5-2e6fbdc8f403.png)

**Comment by Athanasius** [comment] 2020-07-20 18:31
Well, yes, different code is run depending on your selection there.

We did make a few tweaks to `plugins/inara.py` (All Inara, EDDB and EDSM stuff for System/Station is in the internal plugins).  I'll have a look into this tomorrow.

**Comment by cmdrredhouse** [comment] 2020-07-20 18:39
When I changed Station to EDDB, I could no longer click on the System link, was just a circle with a line, so that stopped working. However, I changed BOTH System and Station to EDSM and now it all works! :)

![7-20-2020 11-28-51 AM](https://user-images.githubusercontent.com/68560854/87973671-baaf6100-ca7d-11ea-975f-35caf6c54ed1.png)

**Comment by cmdrredhouse** [comment] 2020-07-20 18:49
Nope, sorry... just stopped working again. I give up.

![7-20-2020 11-28-51 AM](https://user-images.githubusercontent.com/68560854/87974557-19c1a580-ca7f-11ea-846d-731e261d84d9.png)

**Comment by cmdrredhouse** [comment] 2020-07-20 18:54
One last try... I reset my API key for EDSM, but no go. Then I chnaged back to EDDB and all three stats show but when I use EDDB, I cannot click on "System" for some reason.

![7-20-2020 11-28-51 AM](https://user-images.githubusercontent.com/68560854/87974987-ce5bc700-ca7f-11ea-8cbd-9be3fa79ecb2.png)

**Comment by cmdrredhouse** [comment] 2020-07-20 19:02
OK, I got all options working by just setting to EDDB, and closing the EDMC and reopening it. Even closed it again and tried once more and still works. I think it's OK now. Weird but, I don't know much about what's going on behind the program, but right now, it's all working :) Thanks!

**Comment by Athanasius** [comment] 2020-07-20 19:03
I guesss I'll be taking a trip to Sirius tomorrow to see if I can get this bug to reproduce.

**Comment by cmdrredhouse** [comment] 2020-07-20 19:09
Ha! Maybe I'll see you there! Right now, have Station and System set to EDDB and have closed out and restarted the EDMC several times, to TRY to break it but it's holding fine now, Shipyard, System and Station all show and are clickable. Seems to be working fine with EDDB now. I did like INARA option, but I'll live ;) Thanks!

![7-20-2020 12-06-57 PM](https://user-images.githubusercontent.com/68560854/87976368-dae11f00-ca81-11ea-868b-9aa65e1be40e.png)

**Comment by Athanasius** [comment] 2020-07-20 20:26
The weird thing is that it's specifically the EDDB System and Station providers that I changed between 3.4.6.0 and 4.0.0.0.  You'd expect those to be the broken ones if anything.  This also explains why I wouldn't have done quite so much testing of the EDSM and Inara plugins before publishing 4.0.0.0.

Anyway, I'll look at this tomorrow afternoon (unless A_D gets to it before me).

**Comment by cmdrredhouse** [comment] 2020-07-20 20:33
You gotta a bigger brain than me sir, but, I do know that I have "Station" and "System" set to EDDB, and just checked the app, after having it closed for a few hours now and working great! All links working perfectly, with EDDB ;) Thank you for jumping on this. I literally had about one day of it working before an update took out the "Station", Ha! All good. Appreciate all your work!

![7-20-2020 1-28-38 PM](https://user-images.githubusercontent.com/68560854/87983636-8774ce00-ca8d-11ea-9137-be124a1b616c.png)

**Comment by cmdrredhouse** [comment] 2020-07-20 21:45
**Update**: Stopped working again, where I can't click on the "System" name, just a "No Can Do" circle with a line through it.

![hmm](https://user-images.githubusercontent.com/68560854/87989801-8d6fac80-ca97-11ea-99c6-7e536603ea98.jpg)

**Comment by cmdrredhouse** [comment] 2020-07-20 21:49
OK, just closed it and re-opened it and it works again. Ha! Weirdness!

![7-20-2020 2-48-58 PM](https://user-images.githubusercontent.com/68560854/87990118-39b19300-ca98-11ea-9a92-48da79b2aa98.png)

**Comment by Athanasius** [comment] 2020-07-20 21:53
@cmdrredhouse It's obvious you're testing just with Patterson Enterprise in Sirius.  I'll get over there and see if I can reproduce tomorrow.

BUT.  Next time this happens *immediately*:

1. Attach `%TEMP%\EDMarketConnector.log` to a comment here.
1. Attach your latest journal file from `shell:SavedGames\Frontier Developments\Elite Dangerous\` **NB: Might contain things you consider to be private.**
1. Attach the output of 'File' > 'Save Raw Data'. **NB: Might contain things you consider to be private.**

The first will show if any errors are being logged.  The 2nd and 3rd are the data that EDMC will have used to produce the state you're seeing.  If you're paranoid about their contents then you can email them to me: github@miggy.org

**Comment by cmdrredhouse** [comment] 2020-07-20 22:22
You got it! I just fired it up and tested it and it's working fine, but, should it "stop", I will collect that data for you. Thanks! :)

**Comment by cmdrredhouse** [comment] 2020-07-20 22:26
And yes, I have been testing with Sirius in this post, but it was the same hit and miss last night in another system and from many other systems since that first update of two, just an FYI. I will be on the move tonight and can test from a few other locations. Thnx!

**Comment by cmdrredhouse** [comment] 2020-07-20 22:48
Still working, but I did notice this "EDDN Messages Logs", clicked on it and see these "**Not Horizon**". Just wondering if this means anything to you, that might be helpful?

![7-20-2020 3-45-20 PM](https://user-images.githubusercontent.com/68560854/87993810-55209c00-caa0-11ea-82a3-a8d457657088.png)

**Comment by cmdrredhouse** [comment] 2020-07-20 23:17
Checking in from **Procyon**. Still working fine and was updating new location before ship even hit the pad! :)

![7-20-2020 4-15-32 PM](https://user-images.githubusercontent.com/68560854/87995486-800cef00-caa4-11ea-9f38-4ba634de8de1.png)

**Comment by cmdrredhouse** [comment] 2020-07-21 01:59
Checking in from Kuwemaki @ The Jet's Hole. Still working! :)

![7-20-2020 6-57-43 PM](https://user-images.githubusercontent.com/68560854/88004035-10562e80-cabb-11ea-9dc6-499ed32cc92e.png)

**Comment by Athanasius** [comment] 2020-07-21 16:52
Can you please test this Release Candidate.  I found the bug, but then started digging into a few other cleanups and enhancements as well.  You should switch back to Inara as your provider.

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.3-rc1

**Comment by cmdrredhouse** [comment] 2020-07-21 17:20
Sure thing. Just need about about 30 minutes and will let you know.

Thanks!

Get BlueMail for Android<http://www.bluemail.me/r?b=15860>
On Jul 21, 2020, at 9:52 AM, Athanasius <notifications@github.com<mailto:notifications@github.com>> wrote:

Can you please test this Release Candidate. I found the bug, but then started digging into a few other cleanups and enhancements as well. You should switch back to Inara as your provider.

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.3-rc1

**Comment by Athanasius** [comment] 2020-07-21 17:20
There's a small error in edsm.py preventing that from working.  I'll put out -rc2 shortly to fix the missing line.

**Comment by Athanasius** [comment] 2020-07-21 17:30
Please now use https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.3-rc2

**Comment by cmdrredhouse** [comment] 2020-07-21 17:48
Hello. So, I installed it and it no longer seems to work with EDDB, if I use EDDB it doesn't show where I am at (System name), just ship name, so I switched to INARA and seems to work fine. It does not show where I am at until I hit the Update option. I am not currently at a station and will not be until much later tonight, so not sure 'bout that until later tonight. I am in the middle of re-logging some Guardian materials. I am wondering, if it possible to add, along with "Station", a coordinate system for the planet you're on? I am sitting outside the perimeter of a Guardian site right now, would be cool if it gave those coordinates or at least planet, but, all looks good with INARA, so far. I'll test a "Station" later. Thank you! Also, and have no idea how this works, but when you go to install _any_ version, Windows throws a block and you have to tell it to Run anyway. Hope this helps :)

![7-21-2020 10-34-26 AM](https://user-images.githubusercontent.com/68560854/88088559-7389a480-cb3f-11ea-9aac-7cb8b3e93c0e.png)

![version](https://user-images.githubusercontent.com/68560854/88088573-7ab0b280-cb3f-11ea-9e8b-4c46b0458011.png)

![connector](https://user-images.githubusercontent.com/68560854/88088584-7e443980-cb3f-11ea-97b9-109ca0a98259.png)

**Comment by Athanasius** [comment] 2020-07-22 09:27
**NB: if installing 4.0.3-rc2 (or any later) you must first explicitly Uninstall the application if coming from a previous 4.0.3-rcX version.**

Basically msiexec (the program in Windows that actually does the installing) sees "4.0.3.0" for any of these release candidates, and thus might not do the right thing when upgrading in-place (because it doesn't really think it's an upgrade).

If only msiexec (and a few other bits) would actually support proper full Semantic Version strings then we wouldn't have this problem.

**Comment by Athanasius** [comment] 2020-07-22 11:11
Here's the testing I just did with the 4.0.3-rc2 source in PyCharm Debugger, using 'eddb' for both system and station provider (this is doubling up as notes for the unit tests we need to add to make this easier in the future).

    [11:45] Athanasius (EDMC/ed.miggy.org) : With eddb as both providers:

    1) Exited game in space in an uninhabited system
    2) Exited EDMC.
    3) Re-ran EDMC (this time under pycharm debugging, using the Release/4.0.3-rc2 and a git stash push)
    4) Log back into game fully.

    And as expected System name shown, the EDSM status lookup even succeeded, blank Station, 'cos there's none in the system (well, system pop is zero).
    [11:45] Athanasius (EDMC/ed.miggy.org) : So I have to assume that https://github.com/EDCD/EDMarketConnector/issues/616#issuecomment-662010736 hit the RC upgrade issue and was still actually using -rc1 plugin files.
    [11:46] Athanasius (EDMC/ed.miggy.org) : Still working as expected after jump to another zero pop system
    [11:48] Athanasius (EDMC/ed.miggy.org) : Expected behaviour when jumping to a populated system (both system and station links go to EDDB system page via system-address, station shows the 'x').
    [11:50] Athanasius (EDMC/ed.miggy.org) : exiting game, no change as expected.
    Re-running game.  Cmdr/Ship blank by the main menu, system and station don't and probably should, but relatively harmless.
    Going full in-game works as expected.
    [11:52] Athanasius (EDMC/ed.miggy.org) :
    Restarting both (EDMC first once both exited):
    Initially EDMC shows Cmdr/Ship as usual, but no system/station as expected.
    During game startup Cmdr/Ship then blank, as expected.
    Once fully in-game everything on the UI populates and links work as expected.
    [11:55] Athanasius (EDMC/ed.miggy.org) : And as expected travelling to, and docking with a station (Docking Request fills in the station name, link works then, also stays same after docking).
    [11:57] Athanasius (EDMC/ed.miggy.org) : Re-start of EDMC whilst still in-game and docked works as expected.
    [11:58] Athanasius (EDMC/ed.miggy.org) : Back to station 'x' after undocking, as expected.
    [11:59] Athanasius (EDMC/ed.miggy.org) : Same after restart of EDMC in that state (game running, floating outside station after undock).
    [11:59] Athanasius (EDMC/ed.miggy.org) : (Are you yet appreciating all the state changes that will need to end up in unittests :slight_smile: ? )
    [12:00] Athanasius (EDMC/ed.miggy.org) : Jump to zero pop turned out as expected.
    [12:00] Athanasius (EDMC/ed.miggy.org) : As did an EDMC restart in that state (in supercruise in zero pop system).

**Comment by Athanasius** [comment] 2020-07-22 11:21
Journals from the above testing.

[Journal.200722114409.01.log](https://github.com/EDCD/EDMarketConnector/files/4959664/Journal.200722114409.01.log)
[Journal.200722114912.01.log](https://github.com/EDCD/EDMarketConnector/files/4959665/Journal.200722114912.01.log)
[Journal.200722115117.01.log](https://github.com/EDCD/EDMarketConnector/files/4959666/Journal.200722115117.01.log)

**Comment by cmdrredhouse** [comment] 2020-07-22 22:27
I just checked the EDMC and this is now what I get. Stopped working again?

![7-22-2020 3-25-59 PM](https://user-images.githubusercontent.com/68560854/88235472-c93d7a00-cc2f-11ea-9469-4c50d9c3654f.png)

**Comment by cmdrredhouse** [comment] 2020-07-22 22:35
Hmm, I don't know... I closed it and tried again and same "Unable to get Endpoint / Profile", but I clicked on Update, twice, the first time, 
![7-22-2020 3-34-10 PM](https://user-images.githubusercontent.com/68560854/88236045-fe969780-cc30-11ea-9032-b2025061a291.png)
same message, the second time... it worked and I got below.

**Comment by Athanasius** [comment] 2020-07-22 23:18
The `unable to get endpoint /profile` is a red herring.  It's caused by the Frontier CAPI servers not responding within 10s.  All of this works off the Journal files once you're in-game anyway.

So, please:

1) Confirm you **uninstalled* EDMC first.
2) Then installed 4.0.3-rc2.
3) And have then either been testing fully in-game, or have taken Frontier CAPI servers sometimes not responding into account.

**Comment by cmdrredhouse** [comment] 2020-07-23 02:55
Hi. Just so I am clear. Remove the version I have? It's working fine, it looks like, right now, but, if you don't mind, putting a link to the whatever version I should be using, I'll go ahead and uninstall and install whatever version you send me a link to. Thank you!

**Comment by cmdrredhouse** [comment] 2020-07-23 08:25
I've been all over the galaxy tonight and still working fine.

![7-23-2020 1-19-57 AM](https://user-images.githubusercontent.com/68560854/88266000-4b0ac300-cc83-11ea-912a-b8a6b1a81b9e.png)

**Comment by Athanasius** [comment] 2020-07-23 08:27
> Hi. Just so I am clear. Remove the version I have? It's working fine, it looks like, right now, but, if you don't mind, putting a link to the whatever version I should be using, I'll go ahead and uninstall and install whatever version you send me a link to. Thank you!

Oh, if it's working fine, then no need.  Just we had some reports of people installing 4.0.3-rc2 over 4.0.3-rc1 and not actually getting the updated plugin files, we think because Windows sees both as 4.0.3.0 (it doesn't actually support Semantic Versions).  Keep this in mind if you switch from EDDB providers to EDSM.

**Comment by Athanasius** [comment] 2020-07-24 12:20
Closed as [4.0.3](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.0.3) is now out.

**Closed by Athanasius** 2020-07-24 12:20 UTC
Labels: bug
