### ISSUE TITLE
"UnboundLocalError: local variable 'r' referenced before assignment" whithout internet connection

### ISSUE THREAD

**Issue by leonardofelin** [EDCD/EDMarketConnector#1132] opened 2021-06-02 11:35 UTC
**Describe the bug**
EDMC displays "**local variable 'r' referenced before assignment**" when starting up without internet connection.

**To Reproduce**
1. Disable network access
2. Start EDMC
3. See error message at the bottom of the EDMC window

**Comment by leonardofelin** [comment] 2021-06-02 11:38
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6584149/EDMarketConnector-debug.log)

Attached. Error at 2021-06-01 21:53:31.812

**Comment by hypertasker** [comment] 2021-06-18 17:18
This issue still exists. It shows up like shown in the picture below, doesn't update plugins FCMS or INARA. 
![image](https://user-images.githubusercontent.com/67942070/122596119-09e38480-d087-11eb-9730-86a9c8dc2895.png)

**Comment by wegotourselvesareader** [comment] 2021-08-21 09:45
Confirmed. Just happened to me here. I launched EDMC before waiting for the network connection to be fully up, and can see the same message as above. Not sure if it will affect operation of EDMC, now that the network connection is online, or if I should quit and reload EDMC before loading the game.

**Comment by coniuc2d** [comment] 2021-09-25 22:36
Im running caching squid on my local network with ports 1000-65000 marked as safe. Same issue. If i shut down squid problem disappears.
This is from access.log:
26/Sep/2021:00:33:27 +0200      0 192.168.1.221 NONE/000 0 NONE error:transaction-end-before-headers - HIER_NONE/- -

192.168.1.221 is my gaming machine with EDMC and elite running.

I have no idea about programming though.

**Comment by Athanasius** [comment] 2021-11-10 10:03
Finally looked at this in debugger.  I think the `UnboundLocalError: local variable 'r' referenced before assignment` is simply because of the `self.dump(r)` there.  So a simple adjustment shoudl get rid of the error.  You're still going to get *some* sort of error showing up in the status bar though, as the CAPI Refresh -> Access Token failed.

**Comment by Athanasius** [comment] 2021-11-13 11:12
Fixed in https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.2.2

**Closed by Athanasius** 2021-11-13 11:12 UTC
Labels: bug, unconfirmed
