### ISSUE TITLE
list index out of range thrown after scanning a new nav beacon

### ISSUE THREAD

**Issue by Tenzian** [EDCD/EDMarketConnector#926] opened 2021-03-21 15:16 UTC
**Please complete the following information:**
 - Version [e.g. 4.0.6 - See 'Help > About E:D Market Connector'.  If running from source using git then please paste the output of `git log --decorate=full | head -1`]

    ```commit 22811adf3098f6216fa09eca3589588996c8f0a7 (HEAD -> refs/heads/stable, tag: refs/tags/Release/4.2.3, refs/remotes/origin/stable, refs/remotes/origin/release-4.2.3, refs/remotes/origin/main, refs/remotes/origin/HEAD)```
 - OS: macOS 11.2.3 (Big Sur): Python 3.9.2 (Homebrew 3.9.2_2)
 - OS Locale: English

 - Please attach **BOTH** log files as follows:

Only the debug log is present & It doesn't show up in that log, but does in the terminal window where EDMC is running (log going straight to STDERR?). I've included the line before to give context if comparing with the debug.log:
```
2021-03-21 13:38:21.879 - DEBUG - monitor.EDLogs.get_entry:842: Called with no event_queue
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/Users/tenz/Repositories/EDMarketConnector/plugins/eddn.py", line 188, in sendreplay
    cmdr, msg = json.loads(self.replaylog[0], object_pairs_hook=OrderedDict)
IndexError: list index out of range
```
  
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6177629/EDMarketConnector-debug.log)

**Describe the bug**
The error seems to have no effect on the running of EDMC itself. 
I don't know if this would have a knock on effect to journal data being submitted to EDDN.

**To Reproduce**
1. Go to an inhabited system you have not visited before
2. Scan the nav beacon
3. Jump to supercruise within the same system.
4. See list index out of range error

**Comment by Athanasius** [comment] 2021-03-22 09:01
> Only the debug log is present & It doesn't show up in that log, but does in the terminal window where EDMC is running (log going straight to STDERR?). I've included the line before to give context if comparing with the debug.log:

Aside: Yeah, the instructions were never right for Linux (the application has never been packaged for it, nor a shell script provided to redirect for you).  I've fixed up that entire [section of Troubleshooting](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#plain-log-file).

**Comment by Athanasius** [comment] 2021-03-22 09:06
> ```
> 2021-03-21 13:38:21.879 - DEBUG - monitor.EDLogs.get_entry:842: Called with no event_queue
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
>     return self.func(*args)
>   File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 814, in callit
>     func(*args)
>   File "/Users/tenz/Repositories/EDMarketConnector/plugins/eddn.py", line 188, in sendreplay
>     cmdr, msg = json.loads(self.replaylog[0], object_pairs_hook=OrderedDict)
> IndexError: list index out of range
> ```

Assuming you did pick that out at the correct time...

> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to an inhabited system you have not visited before
> 
>     2. Scan the nav beacon
> 
>     3. Jump to supercruise within the same system.
> 
>     4. See list index out of range error

... then these are unlikely to be reproduction steps.  The traceback is from the code for loading Journal events that failed to send to EDDN previously.  It *looks* like `self.replaylog` is still a list, but empty.  I'll take a closer look at the code a little later today.

**Comment by Tenzian** [comment] 2021-03-22 11:06
it does appear every time just after entering supercruise when I scan a nav beacon I've not been to before. 

But, the scanning of the nav beacon may well be a red herring: Scanning the beacon is something I always do when visiting new places so it may be a post hoc fallacy & this is a symptom of something else entirely 😁 

I'll keep an eye out and see if it happens at any other times.

**Comment by Athanasius** [comment] 2021-03-22 11:08
Well, this is perplexing.  They way `self.replaylog` is initialised and used means that by line 188 of plugins/eddn.py it has to be a list with at least one member.  That would be at index 0, so there can't possibly be an index error there.

The traceback is that line though, so it's not an exception thrown by the `json.load()` itself.

The reason for no debug.log output is because we only catch JSONDecodeError for that call.

We *think* this is something to do with `update_idletasks()` (called to actually update the status line text to what we just changed it to) calling into `sendreplay()` again.

So, we'll add an additional check on `self.replaylog`, with logging, to return if it's false after the idletasks update.

**Comment by Athanasius** [comment] 2021-03-22 11:52
@Tenzian Please pull and checkout latest `main` to see if we at least catch this.  You'll need to check debug.log for output caused by:

```python
            logger.error(
                f'self.replaylog (type: {type(self.replaylog)}) is falsey after update_idletasks().  Traceback:\n'
                f'{"".join(traceback.format_list(traceback.extract_stack()))}')
```
i.e. text "self.replaylog (type: <some type>) is falsey after update_idletasks(). Traceback:" and then the traceback.

**Comment by Tenzian** [comment] 2021-03-22 13:21
👍 will have a go after work

**Comment by Athanasius** [comment] 2021-03-22 16:26
A heads up in case you're specifically using `main`: https://github.com/EDCD/EDMarketConnector/discussions/929

Although I think you probably know how to easily back out if you decide to try out either `develop` or continue with `main` after the merge.

**Comment by Tenzian** [comment] 2021-03-22 19:45
I got this one after jumping in to _Col 285 Sector AU-X b15-4_ and honking:

```
2021-03-22 19:37:15.596 - DEBUG - monitor.EDLogs.get_entry:842: Called with no event_queue
2021-03-22 19:37:16.433 - ERROR - plugins.eddn.EDDN.sendreplay:190: self.replaylog (type: <class 'list'>) is falsey after update_idletasks().  Traceback:
  File "/Users/tenz/Repositories/EDMarketConnector/EDMarketConnector.py", line 1382, in <module>
    root.mainloop()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1429, in mainloop
    self.tk.mainloop(n)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 814, in callit
    func(*args)
  File "/Users/tenz/Repositories/EDMarketConnector/plugins/eddn.py", line 192, in sendreplay
    f'{"".join(traceback.format_list(traceback.extract_stack()))}')

2021-03-22 19:37:26.734 - DEBUG - monitor.EDLogs.get_entry:842: Called with no event_queue
```

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6184902/EDMarketConnector-debug.log)

**Comment by Tenzian** [comment] 2021-03-22 19:59
and a whole mess of them in _Brestla_ after scanning the nav beacon and jumping to supercruise:


[EDMarketConnector-debug.log.1.log](https://github.com/EDCD/EDMarketConnector/files/6184978/EDMarketConnector-debug.log.1.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6184982/EDMarketConnector-debug.log)

**Comment by Athanasius** [comment] 2021-03-22 20:47
Wow, at this stage I'm surprised it's not crashing from blowing through the stack....

Ah, I see what's happening.  You have the EDDN option `Delay sending until docked` either active now, or have in the past ?  This file is used for that too.

Now, you being on macOS that file would be ... `~/Applications/EDMarketConnector/replay.jsonl` I think.  It's going to be easier to diagnose and test this if you're happy to supply your file.  Else I'll have to take some time to either play and generate one or hand-craft one for testing.

**Comment by Athanasius** [comment] 2021-03-22 21:13
And the more I think about this code the more it needs a re-write.  If nothing else this being on the main thread means there's always the chance of one of the `send()` calls hanging until timeout, pausing the whole EDMC UI in the meantime.

It needs to be proprerly threaded, and then there wouldn't be this tk timer nonsense anyway.

But, as we're in code freeze pending Odyssey work for now we need to patch around this.  Tbh, it might be a cause of us having identified what caused the original exception, and just lose the logging we added now.  Slap a big TODO on it, and move on.

**Comment by Tenzian** [comment] 2021-03-22 23:18
I do have a `~/Library/Application Support/EDMarketConnector/replay.jsonl` file, but it's zero bytes.

I don't _think_ I ever used the _delay sending until docked_ option: I can't see an entry in `~/Library/Preferences/uk.org.marginal.edmarketconnector.plist` that looks like it would enable it.

![Screenshot 2021-03-22 at 23 15 33](https://user-images.githubusercontent.com/13963952/112069864-84723600-8b64-11eb-94b7-3d3c23969638.png)

**Comment by Tenzian** [comment] 2021-03-22 23:47
I tailed the file while playing and there is stuff going in to it:

[tailed replay.jsonl.txt](https://github.com/EDCD/EDMarketConnector/files/6185917/tailed.replay.jsonl.txt)

Just after the last entry I got a bunch of errors and the file's back to zero bytes again.

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/6185925/EDMarketConnector-debug.log)

**Comment by Tenzian** [comment] 2021-03-23 01:49
I've watched it happen a few more times now & the supercruise jump is a complete red herring.

It looks to me like the error messages occur a few seconds after _replay.jsonl_ reaches a particular size, regardless of what you're doing; I guess scanning a new beacon just fills it up quickly with `NavBeaconDetail` events.

If I was to guess I'd be pointing a finger at a routine that's processing replay.jsonl continuing to attempt to do so after the file is reduced to zero bytes, hence the empty list & index error.

**Comment by Athanasius** [comment] 2021-03-23 08:49
Ah, now I recall that there are other reasons for EDDN stuff to go through the replay file.  I wonder if you're the only person paying enough attention to see the status line error message, or if you have slightly slow connection to EDDN, or something else is tripping into this more than others.

We're confident the cause of the actual original error is double-calling of the function (the function itself does something that *can* cause itself to be called again in a chain).  Then it's up to a race condition between that and the timer for the function being called.  The spam of logging you're now seeing is indicative of just how deeply the calls to the function are being nested.

I'll update `main` to no longer have the logging, just a return at that point, so things will at least work, even if not in the way design intended.

**Comment by Tenzian** [comment] 2021-03-23 12:57
> I wonder if you're the only person paying enough attention to see the status line error message

I'll go with this one: It's not functionally impacting and I suspect not many people run EDMC with the log scrolling away in a window next to it 😏

**Comment by Athanasius** [comment] 2021-03-23 14:36
The fix (no logging, just the return) is in https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.2.4 which will shortly be merged into `main` and `stable`.  Reminder: Some time tomorrow `develop` is being merged into `main`.

**Closed** 2021-03-24 13:46 UTC
Labels: bug, unconfirmed
