### ISSUE TITLE
First authentication attempt just looping

### ISSUE THREAD

**Issue by Just-Reporting** [EDCD/EDMarketConnector#2306] opened 2024-09-30 08:09 UTC
**System info**

 - Version: 5.12.0+cc6e200
 - Game Version: Live
 - OS: Windows 10
 - OS Locale: English
 - Browser: Firefox, Edge and Brave

**Bug**
Trying to authenticate EDMC for the first time with Frontier.
EDMC opens an auth window in the default browser.
Login with username and password.
Browser gives a popup checking it's OK to allow the EDMC link to be opened by EDMC application.
Allow it.
Nothing happens.
Check the log file and:
_2024-09-30 07:26:39.696 UTC - INFO - 29904:36436:36436 journal_lock.JournalLock._obtain_lock:109: Exception: Couldn't lock journal directory "C:\Users\strin\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2024-09-30 07:26:39.706 UTC - INFO - 29904:36436:36436 EDMarketConnector.__main__:344: An EDMarketConnector.exe process was already running, exiting._

No popup appears - UI just does nothing.

Closing EDMC application and reclicking on the browser button to open EMDC, does cause it to reopen - but EDMC then immediately opens a new auth request tab in the browser, and repeats the above.
In the logs there's a corresponding entry:
_2024-09-30 07:24:43.091 UTC - DEBUG - 51304:35312:35312 companion.Session.login:720: We do NOT have an access_token_
even though that (presumably successful, as it opened the application) callback should have included the token?
 
Tried repeatedly with all combinations of:
Browser: Edge, Brave, Firefox
--suppress-dupe-process-popup start up param included/not included
Username/Password and Steam Authentication
Closing EDMC after initial attempt, or leaving it running and just spamming the button in the Auth browser tab
Fully logged in to the game, sat at main menu prompt, or logged out.

Exactly the same results with every attempt. 

The UI shows the correct CMDR name, ship name and System, but is "Awaiting full CMDR login", regardless of whether I am fully logged in to the game and playing, sat at main menu prompt, or logged out.

- [X ] I have checked the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) list to ensure this is not a duplicate
- [ X] I have checked the [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting) to check for known workarounds

**Logs**

[EDMarketConnector.log](https://github.com/user-attachments/files/17186151/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17186152/EDMarketConnector-debug.log)

**Comment by Rixxan** [comment] 2024-09-30 22:45
Potential root cause identified, working on full fix. Tracking in #2303

**Comment by Rixxan** [comment] 2024-10-01 03:14
I believe this issue to be resolved.

Testing a fix in the Beta track right now. Please feel free to test and let me know if the issue persists!

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc2

**Comment by Rixxan** [comment] 2024-10-03 00:10
Fixed in latest release https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1

**Closed by Rixxan** 2024-10-03 00:10 UTC
Labels: bug, awaiting feedback

**Comment by Just-Reporting** [comment] 2024-10-04 06:25
Can confirm that this is working perfectly in the 5.12.1 release - thank you.
