### ISSUE TITLE
Since Latest version, EDMC fails to authenticate via Steam

### ISSUE THREAD

**Issue by gabolander** [EDCD/EDMarketConnector#2307] opened 2024-09-30 09:13 UTC
My environment:
 
 - Version: 5.12.0
 - Game Version: Odyssey
 - OS: Windows 10
 - OS Locale: Italian
 - If applicable: google chrome

[//]: # (A clear and concise description of what the bug is.)
Hi there, after the recent update (almost a week ago), EDMC starts asking me the authentication with Frontier (to grant permission to EDMC evidently), as happened several times. But this time it's not working.
1. The Frontier authenticaton page appears on my browser
![Acc1](https://github.com/user-attachments/assets/32290207-f5af-4e90-b3ca-d8a32a9cdd8b)

3. I have a Steam account, so I click on Steam Icon
![Acc2](https://github.com/user-attachments/assets/58f0add4-278a-401e-90b3-2d5d3b2d8881)

5. The steam authentication page appears, (and I'm already logged in) and I click to "Log in". After the first click ... nothing happens.
6. As I click a second time, Steam gets a "Invalid access data" error"
![Acc3](https://github.com/user-attachments/assets/d352f0e3-7bdd-44d7-9e58-dd0c7d7b0e31)

All the others authorizations to Frontier sites via Steam (store, forum) using the same mechanism, work perfectly.

I noted that EDMC logs anyway my positions and seems to be up and working (BGS Tally is updated, my EDSM and Coriolis profile are updated as well). But each time I enter in game in Elite Dangerous, EDMC keeps asking me authorization on Frontier->Steam which always fails.

Thanks in advance for any help.

**Comment by gabolander** [comment] 2024-09-30 16:05
It seems I've solved following the instructions of @Tarmstrong7 in this comment: 
https://github.com/EDCD/EDMarketConnector/issues/2303#issuecomment-2381017729

Thank you mates!
G.

**Comment by Rixxan** [comment] 2024-09-30 22:44
Potential root cause identified, working on full fix.

**Comment by Rixxan** [comment] 2024-10-01 03:13
I believe this issue to be resolved.

Testing a fix in the Beta track right now. Please feel free to test and let me know if the issue persists!

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc2

**Comment by gabolander** [comment] 2024-10-01 07:23
> I believe this issue to be resolved.
> 
> Testing a fix in the Beta track right now. Please feel free to test and let me know if the issue persists!
> 
> https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc2

Hi there mate.
Just tested the 5.12.1-rc2 (5.12.1-rc2+0cfc487). It ran flawlessly!! "**Authentication succesfull**"

Thank you very much. Keep on the excellent work!

Only a question now: when there will be the next stable version, does it recognize alone and notify me to update EDMC?

Tnks again 4 all!
G.

**Comment by Rixxan** [comment] 2024-10-01 11:20
Hey there!

Glad to hear it's working. You should receive the next update pushed to
either Live or Beta track (depending on how you have it set in settings)
just like any other update.

I'll gather a bit more data and then hopefully get this out the door in the
next day or two.

**Comment by Rixxan** [comment] 2024-10-03 00:10
Fixed in 5.12.1. 
https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1

**Closed by Rixxan** 2024-10-03 00:10 UTC
Labels: bug, awaiting feedback
