### ISSUE TITLE
"INARA: The reputation value exceeds the valid range" error

### ISSUE THREAD

**Issue by auslambert** [EDCD/EDMarketConnector#499] opened 2020-06-06 20:33 UTC
I've been getting this a lot lately. It doesn't seem to affect the app or gameplay but seems like every star system I visit that I'm friendly with pops it up.

[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/4740944/EDMarketConnector.log)

Since this is the first bug I've reported I'll paste the log contents as well as attach the file... in case the drag & drop went wrong.

Inara	400 The reputation value exceeds the valid range.	{"eventName": "setCommanderReputationMinorFaction", "eventTimestamp": "2020-06-06T20:23:00Z", "eventData": [{"minorfactionName": "Pilots' Federation Local Branch", "minorfactionReputation": 57.841599}, {"minorfactionName": "Democrats of Pangluya", "minorfactionReputation": 0.0}, {"minorfactionName": "Pangluya Vision Group", "minorfactionReputation": 0.0}, {"minorfactionName": "LHS 295 Dynamic Company", "minorfactionReputation": 0.0}, {"minorfactionName": "Bureau of Pangluya", "minorfactionReputation": 0.0}, {"minorfactionName": "Pangluya Purple Power Co", "minorfactionReputation": 0.0}, {"minorfactionName": "Pangluya Cartel", "minorfactionReputation": 0.0}, {"minorfactionName": "Remlok Industries", "minorfactionReputation": 0.0}]}

**Comment by pwerken** [comment] 2020-06-08 11:51
This is a duplicate of #475, which has a fix in the assoiciated pull-request.

If you are running EDMC from a git checkout, you could manual apply te change in it.
Otherwise you'll have to wait until the fix gets included in a new release.

**Comment by Athanasius** [comment] 2020-06-20 09:00
Close as dupe of #475

**Closed by Athanasius** 2020-06-20 09:00 UTC
