### ISSUE TITLE
Pre-Release 4.1.0-beta2 ... scaling not working

### ISSUE THREAD

**Issue by FJRMaverick** [EDCD/EDMarketConnector#692] opened 2020-09-10 14:43 UTC
Happy to see this beta and immediately wanted to test the scaling function, but cannot move the scaling slider, so no scaling happening.

Changed the ui-settings in registry to 2.0 and ... surprise ... works in the wrong direction, everything getting even smaller. Tried negative values, which leads to not starting again.

**Comment by Athanasius** [comment] 2020-09-10 16:00
We're aware of this and there should be a beta3 out shortly fixing this issue.

It comes down to a bug in tk/tkinter where any locale not using a `.` as the decimals separator will work because the tk-internal code is recording values with the locale separator but then not parsing them back correctly.

**Comment by Athanasius** [comment] 2020-09-10 16:27
Please try https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.0-beta3

**Comment by FJRMaverick** [comment] 2020-09-10 23:26
Yes, this version works much better.
Dunno whether this is intended behaviour: if I set the scaling to 170 it is the same as default (0), less than 170 yields in a smaller window, more than 170 in a bigger window (this with a screen resolution of 1920x1080).

**Comment by Athanasius** [comment] 2020-09-11 07:21
The 0/170/greater behaviour is expected.  It all depends on what your tk:scaling factor was to start with, which depends on the actual DPI of the monitor (which depends on both the resolution and physical size).

What I'll attempt to look at is why your scale bar is so squished up like that.  I think I might need to get a bit meta and specify its width scaled as per the current tk scaling, as it's in pixels....

**Comment by FJRMaverick** [comment] 2020-09-11 10:29
![image](https://user-images.githubusercontent.com/57774924/92912675-4d3f0180-f42a-11ea-8fed-2d7c7f050915.png)

This is a screenshot taken in FullHD ... everything looks nice. It's all a thing of scaling, which it should solve ;-)

**Comment by Athanasius** [comment] 2020-09-11 11:45
There'll be a fresh beta this afternoon with things changed again so it should work better for utilising the OS scaling as well.  Check the changelog notes :) .

**Comment by Athanasius** [comment] 2020-09-11 13:46
Please test https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F4.1.0-beta4

**Comment by FJRMaverick** [comment] 2020-09-11 14:43
Nice, now is does exactly what it should do, with one exception: the combo boxes are still not resizing and remain small and thus are somewhat difficult to see, which one is selected in high res on a big TV-Screen, some meters away.

![image](https://user-images.githubusercontent.com/57774924/92939342-f2b79c80-f44d-11ea-86e5-df6b534dfff9.png)

**Comment by Athanasius** [comment] 2020-09-11 14:45
I'm not sure there'll be anything we can do about that, given we're applying the scale change globally.  I'd guess it might be that those actually come from a font and perhaps we can change it from the default one.  Will have a look at it tomorrow.

**Comment by FJRMaverick** [comment] 2020-09-11 14:47
fine, thanks for the good work so far

**Comment by FJRMaverick** [comment] 2020-09-11 14:57
Trying to show, what the problem is. On the following picture the scaling of EDMC is set to 100% (as I said, the boxes stay at this size, when upscaling)

![IMG_20200911_165109_9](https://user-images.githubusercontent.com/57774924/92940745-c56bee00-f44f-11ea-9c35-263e4d35f05f.jpg)

**Comment by Athanasius** [comment] 2020-09-11 15:01
The *weird* thing is that in your prior pic it's *both* Default and Dark that have a tiny radio button, one selected, one not, whilst Transparent appears to have a properly scaled one.

*Maybe* there's something subtly different with how they're specified.

**Comment by FJRMaverick** [comment] 2020-09-11 16:46
As I said: The radio button "Transparent" is the only one, which has a "good" sizing, but it get's small as soon as hoovering with the mouse over it  (or the word "Transparent". Yes ... weird.

**Comment by Athanasius** [comment] 2020-09-19 08:08
Now I re-read.  You're saying that this radiobutton issue appears at some level of Windows OS scaling, with EDMC still at 100% ?  In that case I really don't think there's anything we can do about it, as we're not even telling tk to scale in that configuration.

**Comment by Athanasius** [comment] 2020-09-22 08:15
Well, I can't reproduce the under-sized radio buttons with either 125% or 150% scaling.  I *do* see the 'Transparent' one being *over*sized until I mouse over it.  Keeping in mind that you can click on the *text* to select the one you want I don't think this is too big of an issue.

It's unfortunate that I can't reproduce the full issue as that means I can't rapidly iterate on changing manifest options to see if EDMC acts any better (see #515 ).

**Comment by FJRMaverick** [comment] 2020-09-22 09:42
Hiya
yes the under-sized radion buttons can only be seen if windows resoulution is higher than Full-HD (1920x1080), and is independent from the scaling of EDMC (it was my main problem from the beginning). Yes it is no problem to click them, but it is really a problem to recognize, whether they are checked or not.

**Comment by FJRMaverick** [comment] 2020-09-22 09:47
Btw: will my beta version automatically update to the next release version, or do I have to update manually?

And one more thing (not related), I often see a message similar to "list object is empty" (cannot remember exactly the wording), which seems to happen if landing in a damaged station or sometimes on a fleet carrier (most probably if not having anything listed in commodity market). I guess the empty market (but existing) market is the reason for the message. But it's not very user friendly, as it seems to be error, where it is only a notice/warning (but user cannot really understand why).

**Comment by FJRMaverick** [comment] 2020-09-22 09:52
I have just looked onto the link you have supplied. Yes, I think this dpi-wareness seems to be the right approach, making the slider osbolete, if the apps respects current windows settings (which it actually does NOT). And most probably will even solve the radio-button problem.

**Comment by Athanasius** [comment] 2020-09-22 10:20
> Hiya
> yes the under-sized radion buttons can only be seen if windows resoulution is higher than Full-HD (1920x1080), and is independent from the scaling of EDMC (it was my main problem from the beginning). Yes it is no problem to click them, but it is really a problem to recognize, whether they are checked or not.

At least the sole use of them in core EDMC is 'obvious'.  Just click the theme you want to be sure it's set ;) .

**Comment by Athanasius** [comment] 2020-09-22 10:23
> Btw: will my beta version automatically update to the next release version, or do I have to update manually?

Yes.

> And one more thing (not related), I often see a message similar to "list object is empty" (cannot remember exactly the wording), which seems to happen if landing in a damaged station or sometimes on a fleet carrier (most probably if not having anything listed in commodity market). I guess the empty market (but existing) market is the reason for the message. But it's not very user friendly, as it seems to be error, where it is only a notice/warning (but user cannot really understand why).

See #671 (it applies to damaged stations as well), it should have been fixed in beta5.

**Comment by Athanasius** [comment] 2020-09-22 10:25
> I have just looked onto the link you have supplied. Yes, I think this dpi-wareness seems to be the right approach, making the slider osbolete, if the apps respects current windows settings (which it actually does NOT). And most probably will even solve the radio-button problem.

No, we currently *already* say we're DPI-aware, when really we're not.  I'll be experimenting later today with that off and possibly some other options on to see if it cures the "until you mouseover" radio button issue (and if it does, hope it fixes you're too-small issue too).

**Comment by FJRMaverick** [comment] 2020-09-22 14:59
> 
> 
> > Hiya
> > yes the under-sized radion buttons can only be seen if windows resoulution is higher than Full-HD (1920x1080), and is independent from the scaling of EDMC (it was my main problem from the beginning). Yes it is no problem to click them, but it is really a problem to recognize, whether they are checked or not.
> 
> At least the sole use of them in core EDMC is 'obvious'. Just click the theme you want to be sure it's set ;) .

yes, your are right regarding core EDMC, but the same applies to any plugin and especially the Cannon plugin has a lot of them ;-)

**Comment by FJRMaverick** [comment] 2020-09-22 15:02
> 
> 
> > Btw: will my beta version automatically update to the next release version, or do I have to update manually?
> 
> Yes.
> 
> > And one more thing (not related), I often see a message similar to "list object is empty" (cannot remember exactly the wording), which seems to happen if landing in a damaged station or sometimes on a fleet carrier (most probably if not having anything listed in commodity market). I guess the empty market (but existing) market is the reason for the message. But it's not very user friendly, as it seems to be error, where it is only a notice/warning (but user cannot really understand why).
> 
> See #671 (it applies to damaged stations as well), it should have been fixed in beta5.

nice, okay not the empty market, but the empty outfitting is the problem causing that ... but my guess was nearby ;-)
Can I obtain the beta's without getting a link from you (still using beta4)?

**Comment by Athanasius** [comment] 2020-09-22 15:15
They're at https://github.com/EDCD/EDMarketConnector/releases

**Comment by Athanasius** [comment] 2020-09-25 15:10
If you're happy using *just* the OS scaling then I think I found the solution to that radio button problem: https://imgur.com/a/KKemdqk

Basically we need to also set 'gdiScaling' true, then those bits scale up correctly.

I'm now wondering if we even need the EDMC scaling, but, eh, I'll leave it in.  It's slightly easier to twiddle it and restart just EDMC than have to sign out and back in to change OS scaling.

**Comment by FJRMaverick** [comment] 2020-10-05 15:24
Just looked at my email and found your last message. Sorry for answering late.
My last beta did not update automatically to release version 4.1.0, so regarding this you were wrong ;-)

But the new scaling is fantastic, thanks for your patience and trying new ways to resolve this issue. It is now perfect.

**Comment by FJRMaverick** [comment] 2020-10-05 15:33
Addition: it's only perfect as long as I leave the slider at 100%, as soon as I lower this things get a bit messed up (text shortened and things like that). Since normal scaling is now working, I tried to scale down a bit (so if used as an "overlay" uses less space in cockpit), but went back to 100% because of the mentioned issue.

**Comment by Athanasius** [comment] 2020-10-05 15:39
> My last beta did not update automatically to release version 4.1.0, so regarding this you were wrong ;-)

That's because, as announced, I've not yet updated the appcast file.

**Closed** 2020-10-05 15:39 UTC
Labels: bug

**Comment by FJRMaverick** [comment] 2020-10-05 16:41
Addition: it's only perfect as long as I leave the slider at 100%, as soon as I lower this things get a bit messed up (text shortened and things like that). Since normal scaling is now working, I tried to scale down a bit (so if used as an "overlay" uses less space in cockpit), but went back to 100% because of the mentioned issue.

Font looks a bit ugly (internal scaling 100%):
![Screenshot (18)](https://user-images.githubusercontent.com/57774924/95107429-31353400-073a-11eb-9bd3-0a18b5067a24.png)

Wishlist: colours adopt to HUD colour (or can be manually changed to same colour)

**Comment by Athanasius** [comment] 2021-04-06 12:55
Still broken with Python 3.9.4.

First time you open Settings > Appearance only the 'Transparent' radio button is scaled up.
Second time you open that, even it isn't scaled up.
