### ISSUE TITLE
Frontier CAPI error

### ISSUE THREAD

**Issue by techno314** [EDCD/EDMarketConnector#2048] opened 2023-08-03 22:12 UTC
**Please complete the following information:**
 - Version: All versions from 5.8.1 and up so far
 - Game Version: Live|Horizons
 - OS: Windows 11
 - OS Locale: English

**Describe the bug**
When you are currently docked at any Fleet Carrier, EDMC will fail update and will spit out the error "Frontier CAPI: Misc. Error"

**To Reproduce**
1. Open EDMC and Elite Dangerous
2. Log into any mode
3. Fly to any Fleet Carrier
4. Dock and press update on EDMC

**Expected behavior**
It should properly update and say "Last updated at xx:xx:xx"

**Screenshots**
![image](https://github.com/EDCD/EDMarketConnector/assets/47404203/685678d1-834d-46c4-acec-dbc606fe193b)

**Additional context**
It does not seem to occur when docking at normal stations and only seems to happen when docked at Fleet Carriers

[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/12255395/EDMarketConnector-debug.log)

**Comment by plscks** [comment] 2023-08-04 13:18
Can confirm this is an issue, I only started noticing it after ED:O Update 16 and updating EDMC to 5.9.2 this week. I haven't played much over the last three months or so but don't recall it giving errors in January-March.

- Version: **5.9.2 - 5.9.3+16ffdffd**
- Game Version: **Elite Dangerous: Odyssey - Live v4.0.0.1600**
- OS: **Windows 11 Pro - 10.0.22631 Build 22631**
- OS Locale: **English**

Relevant logs:

```2023-08-04 12:56:19.989 UTC - ERROR - 2836:19672:19672 companion.capi_single_query:833: Frontier CAPI Auth: GET /shipyard
Traceback (most recent call last):
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\companion.py", line 817, in capi_single_query
    r.raise_for_status()  # Typically 403 "Forbidden" on token expiry
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\.env\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://companion.orerve.net/shipyard
2023-08-04 12:56:19.992 UTC - ERROR - 2836:19672:19672 companion.Session.dump:1123: Frontier CAPI Auth: https://companion.orerve.net/shipyard 500 Internal Server Error {"status":500,"message":"Internal Server Error","tag":"62qxcmd779gqw"}
2023-08-04 12:56:19.993 UTC - ERROR - 2836:19672:19672 companion.capi_single_query:846: Frontier CAPI: Misc. Error
Traceback (most recent call last):
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\companion.py", line 817, in capi_single_query
    r.raise_for_status()  # Typically 403 "Forbidden" on token expiry
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\.env\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://companion.orerve.net/shipyard
2023-08-04 12:56:24.612 UTC - INFO - 2836:18488:18488 plugins.inara.new_worker:1586: sending 7 events for PLSCKS```

Deauthorizing through https://user.frontierstore.net/ and relaunching EDMC to force authorization gets the following in the logs:

```
2023-08-04 13:05:10.789 UTC - INFO - 19120:1896:1896 companion.Auth.authorize:488: Frontier CAPI Auth: New token for "PLSCKS"
2023-08-04 13:05:33.010 UTC - INFO - 19120:14636:14636 plugins.inara.new_worker:1586: sending 6 events for PLSCKS
2023-08-04 13:05:49.267 UTC - ERROR - 19120:17424:17424 companion.capi_single_query:833: Frontier CAPI Auth: GET /shipyard
Traceback (most recent call last):
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\companion.py", line 817, in capi_single_query
    r.raise_for_status()  # Typically 403 "Forbidden" on token expiry
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\.env\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://companion.orerve.net/shipyard
2023-08-04 13:05:49.270 UTC - ERROR - 19120:17424:17424 companion.Session.dump:1123: Frontier CAPI Auth: https://companion.orerve.net/shipyard 500 Internal Server Error {"status":500,"message":"Internal Server Error","tag":"3p46k0q26vpkl"}
2023-08-04 13:05:49.272 UTC - ERROR - 19120:17424:17424 companion.capi_single_query:846: Frontier CAPI: Misc. Error
Traceback (most recent call last):
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\companion.py", line 817, in capi_single_query
    r.raise_for_status()  # Typically 403 "Forbidden" on token expiry
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plsck\PythonProjects\EDMarketConnector\.env\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://companion.orerve.net/shipyard
```

**Comment by connylindquist** [comment] 2023-08-05 13:10
I see this happening outside the carriers too. While in cruise for example.

**Comment by connylindquist** [comment] 2023-08-05 14:09
2023-08-05 14:08:32.245 UTC - INFO - 13332:9220:9220 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.
2023-08-05 14:08:32.328 UTC - INFO - 5588:6872:6872 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Conny\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2023-08-05 14:08:32.357 UTC - INFO - 2948:10836:10836 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.
2023-08-05 14:08:32.482 UTC - INFO - 5588:6872:6872 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.
2023-08-05 14:08:32.495 UTC - INFO - 21936:2572:2572 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.
2023-08-05 14:08:32.750 UTC - INFO - 8816:21092:21092 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Conny\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2023-08-05 14:08:32.783 UTC - INFO - 12852:23084:23084 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Conny\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2023-08-05 14:08:32.821 UTC - INFO - 25196:22028:22028 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Conny\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2023-08-05 14:08:32.917 UTC - INFO - 8816:21092:21092 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.
2023-08-05 14:08:33.041 UTC - INFO - 12852:23084:23084 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.
2023-08-05 14:08:33.097 UTC - INFO - 25196:22028:22028 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.
2023-08-05 14:08:33.156 UTC - INFO - 3856:21628:21628 journal_lock.JournalLock._obtain_lock:106: Exception: Couldn't lock journal directory "C:\Users\Conny\Saved Games\Frontier Developments\Elite Dangerous", assuming another process running: PermissionError(13, 'Permission denied')
2023-08-05 14:08:33.293 UTC - INFO - 3856:21628:21628 EDMarketConnector.__main__:359: An EDMarketConnector.exe process was already running, exiting.

**Comment by techno314** [comment] 2023-08-05 14:20
> I see this happening outside the carriers too. While in cruise for example.

Could there be multiple instances of EDMC running?

**Comment by Rixxan** [comment] 2023-08-06 22:41
I think the issue conny is having is a different error. Spinning that one off for a more immediate fix in #2057

**Comment by connylindquist** [comment] 2023-08-07 05:48
Yea, could have been another issue yes. I solved it temporary by using a flag to use local database (or what it was called) and then it worked fine.

**Comment by halvors** [comment] 2023-08-08 11:14
I can confirm this issue under Linux as well.

**Comment by halvors** [comment] 2023-08-08 11:37
> Yea, could have been another issue yes. I solved it temporary by using a flag to use local database (or what it was called) and then it worked fine.

What flag did you use to make this work?

**Comment by halvors** [comment] 2023-08-08 12:39
I think this issue is because fleet carrier not always offer all services like shipyard etc, if one fails it should still update market etc. Just tested this on another (not my) fleet carrier with shipyard enabled, then there was no errors

**Comment by connylindquist** [comment] 2023-08-08 15:32
"C:\Program Files (x86)\EDMarketConnector\EDMarketConnector.exe" --force-localserver-for-auth   
I used that to start it and it worked fine.

**Comment by plscks** [comment] 2023-08-08 16:48
> I think this issue is because fleet carrier not always offer all services like shipyard etc, if one fails it should still update market etc. Just tested this on another (not my) fleet carrier with shipyard enabled, then there was no errors

Testing this on my own carrier with shipyard (but no ships for sale) and outfitting I still get the CAPI 500 error I reported while docked. It does not seem to error in other systems.

**Comment by Rixxan** [comment] 2023-08-08 18:18
I think the CAPI 500 on Shipyard is indicative of something FDEV changed in U16. No ETA on a fix yet but we'll keep looking into it.

**Comment by techno314** [comment] 2023-08-10 13:58
It seems like this issue has been resolved (for me at least) I will keep this thread open just in case anyone else encounters this error again.

**Comment by Rixxan** [comment] 2023-08-10 17:46
According to sources, the issue was resolved on FDEV side. Closing due to that.

**Closed by Rixxan** 2023-08-10 17:46 UTC
Labels: bug, unconfirmed
