### ISSUE TITLE
Move EDDB, EDSM, Inara system/station tracking into monitor.py

### ISSUE THREAD

**Issue by Athanasius** [EDCD/EDMarketConnector#1042] opened 2021-05-09 14:09 UTC
The necessary might already be tracked in monitor.state.  Ensure it is, and then use *that* rather than all the extra checking in these three plugins.

**Comment by Athanasius** [comment] 2021-05-21 16:22
The problem with this is:

1. plugin `journal_entry()` only gets passed `monitor.state`.
2. Things like "current system we're in" are only on `monitor` (the instance of monitor.py:EDLogs), not in `monitor.state`.
3. Thus plugins can't see the in-monitor tracking of system, station etc.

We can't change the signature of `journal_entry()` without pulling the rug out from under all plugin developers.

We'd have to clear `from monitor import monitor`, or possibly defined access functions, in order for plugins (including core ones) to be able to access this 'class level state'.

**Comment by slippycheeze** [comment] 2023-01-02 19:52
I got a repro on the "Wrong System! Missed jump?" error; is on https://github.com/EDCD/EDMarketConnector/blob/main/plugins/eddn.py#L1230) and the repro was:
1. scan a biological thing from my SRV
2. have just restarted EDMC 
2a. while on the planet I scanned it on
2b. and while sitting in the SRV when I restarted EDMC
3. have not restarted the game

so I suspect the triggering condition is this.systemaddress is None rather than the mismatch path; sadly, it doesn't actually log which, so I can't tell you in any more detail.   (and there is a missed opportunity in debugging. no PR sent for this one)

it is certainly possible this is the cause of all the nasty gong sounds and warnings I've gotten over the last while, and never tracked down.   I'll keep an ear out for more, but I'm pretty sure this is the necessary pattern. (edited)

**Comment by Athanasius** [comment] 2023-01-02 19:53
In case of edits throwing off the code link above, that's in `export_journal_codexentry()`.

**Comment by slippycheeze** [comment] 2023-01-02 21:05
update: similar warning, but without the SRV part, was just in space in my ship.
`2023-01-02 21:02:15.855 UTC - WARNING - 11912:18756:18756 plugins.eddn.EDDN.export_journal_fssdiscoveryscan:1126: SystemAddress isn't current location! Can't add augmentations!`

previous code is https://github.com/EDCD/EDMarketConnector/blob/736a6a5a8355efe94ae5689f9deb01c50285a123/plugins/eddn.py?rgh-link-date=2023-01-02T19%3A52%3A59Z#L1230

new code line is https://github.com/EDCD/EDMarketConnector/blob/736a6a5a8355efe94ae5689f9deb01c50285a123/plugins/eddn.py?rgh-link-date=2023-01-02T19%3A52%3A59Z#L1126

sorry for not linking to the actual blob, but rather the branch, earlier.

**Comment by Rixxan** [comment] 2024-01-04 05:03
@Athanasius Looking at this issue, did #1798 fully solve this, or is there still outstanding work?

**Comment by Athanasius** [comment] 2024-01-04 08:49
> @Athanasius Looking at this issue, did #1798 fully solve this, or is there still outstanding work?

It *should* have yes, given this issue states the problem was related to plugins (including core) not getting data during an EDMC-restart catchup of a Journal file, whereas the monitor.py tracking does and *that* is now used by the core plugins.

**Comment by Rixxan** [comment] 2024-01-04 18:11
Awesome! Given that I think we can close this.

Of course if the issue is not solved, as always someone can reopen and grumble at me :)

**Closed by Rixxan** 2024-01-04 18:11 UTC
Labels: code cleanup
