### ISSUE TITLE
Awaiting Full CMDR Login

### ISSUE THREAD

**Issue by ACAnthis-star** [EDCD/EDMarketConnector#2303] opened 2024-09-28 22:24 UTC
**Please complete the following information:**

[//]: # (You can gather most of this information with the EDMC System Profiler)
 
 - Version: Unknown
 - Game Version: Odyessy
 - OS: Windows 11
 - OS Locale: English
 - If applicable: Browser Chrome/Edge

**Describe the bug**
Despite Authorizing EDMC on frontiers site and being logged into the game in Open and Solo it still says "Awaiting Full CMDR Login" while displaying all of the correct location and CMDR data. It also brings up the Frontier Authentication page every time i disembark, land or adjust something in the settings of EDMC 

**Screenshots**
![Screenshot 2024-09-28 172224](https://github.com/user-attachments/assets/1fc8bff5-c5e4-40be-97a7-27957a47646f)

**Logs**
Please attach both the EDMarketConnector.log and EDMarketConnector-debug.log if available.
[EDMarketConnector.log](https://github.com/user-attachments/files/17176764/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/user-attachments/files/17176765/EDMarketConnector-debug.log)

**Comment by Tarmstrong7** [comment] 2024-09-28 23:01
I just solved this issue so I'll paste my solution here as well

Solved with following steps: 
- Use [release 5.11.3](https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.11.3) although I'm not sure if this is required or not
- Launching the game **AND** entering solo play (loading the game is never stated anywhere even in troubleshooting)
- Launch EDMC by navigating "C:\Program Files (x86)\EDMarketConnector" and running "EDMarketConnector - localserver-auth.bat" (EDMC must be closed)
- If you get an error 500 when attempting to authenticate, select change account and login with Steam

**Comment by ACAnthis-star** [comment] 2024-09-29 01:23
You are amazing sir, immediately resolution. Godspeed CMDR!

**Comment by Rixxan** [comment] 2024-09-29 13:36
Pinning + marking as master ticket for this reported error. Unsure of root cause, continuing to investigate.

**Comment by BerryBlender** [comment] 2024-09-29 19:13
I was also having this issue (first time using EDMC in a long while), @Tarmstrong7's solution has fixed it for me too, thank you kind Commander! <3

**Comment by Rixxan** [comment] 2024-09-30 22:45
Potential root cause identified, working on full fix.

**Comment by Rixxan** [comment] 2024-10-01 03:14
I believe this issue to be resolved.

Testing a fix in the Beta track right now. Please feel free to test and let me know if the issue persists!

https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc2

**Comment by BerryBlender** [comment] 2024-10-01 03:54
> I believe this issue to be resolved.
> 
> Testing a fix in the Beta track right now. Please feel free to test and let me know if the issue persists!
> 
> https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1-rc2

Just updated and everything still works ^-^

**Comment by Rixxan** [comment] 2024-10-01 22:32
Refined RC4 pushed for validation. Was (finally) able to replicate this bug.

**Comment by Rixxan** [comment] 2024-10-03 00:09
Fixed in latest release. https://github.com/EDCD/EDMarketConnector/releases/tag/Release%2F5.12.1

**Closed by Rixxan** 2024-10-03 00:09 UTC
Labels: bug
