### ISSUE TITLE
Release 4.1.3 Silently failing

### ISSUE THREAD

**Issue by TonyFlury** [EDCD/EDMarketConnector#755] opened 2020-10-12 16:42 UTC
Having upgraded from the previous release to Release 4.1.3 on Windows 10, I am unable to run the new release.

There is no error message, and even running the executable from the command line provides no console based errors either.

I have done an entirely clean installation as well and still had no joy.

I don't know how to help diagnose this issue. For the time being I will revert.

**Comment by Athanasius** [comment] 2020-10-12 16:53
Can I ask what path you used to open this issue?  I thought I'd found all the references to the no-template issue form, replacing them with the Bug Report specific one.

**Comment by Athanasius** [comment] 2020-10-12 16:53
As you didn't use the Bug Report template could you please fill it in in a comment here:

**Please check the [Known Issues](https://github.com/EDCD/EDMarketConnector/issues/618) in case this has already been reported.**

**Please also check if the issue is covered in our [Troubleshooting Guide](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting).** It might be something with a known work around, or where a third party (such as EDSM) is causing logging that is harmless.

**Please complete the following information:**
 - Version [e.g. 4.0.6 - See 'Help > About E:D Market Connector'.  If running from source using git then please paste the output of `git log --decorate=full | head -1`]
 - OS: [e.g. Windows 10, Linux Debian 10.6, etc.]
 - OS Locale: [e.g. English, French, Serbian...]
 - If applicable: Browser [e.g. chrome, safari]
 - Please attach log files:
     1. Always attach `%TEMP%\EDMarketConnector.log` from *immediately* after the bug occurs (re-running the application overwrites this file).
     1. If running 4.1.0 (including betas) or later: `%TEMP%\EDMarketConnector\EDMarketConnector-debug.log`.  See [Debug Log File](https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#debug-log-files).
   
   Use the Icon that looks like `_`, `|` and `^` all in one character towards the right of the toolbar above.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by NoFoolLikeOne** [comment] 2020-10-12 17:43
Hey Tony. What plugins are you running?

**Comment by TonyFlury** [comment] 2020-10-12 18:06
Tried it with the Canon plugin, and with None.

BTW - To raise this issue (without a template) I simply clicked on the Issues link at the top of the page.

I have resolved the issue as it seems that this latest installation seems to need a Windows restart (previous updates have not needed that.

**Comment by NoFoolLikeOne** [comment] 2020-10-12 18:30
Does it still happen without the Canonn plugin? We have had problems before . If it happens again please leave a bug report on the Canonn plugin issues section.

**Comment by A-UNDERSCORE-D** [comment] 2020-10-12 19:22
@TonyFlury Regardless. Please fill out our bug report template. Its not there to look pretty.

**Comment by Athanasius** [comment] 2020-10-12 20:50
It's possible this was a case of #678 - the prior EDMC version left a 'zombie' process behind which then got found by the new version, which then tried to raise the now non-existent window and then exited.

I'll look into adding some code to make a popup appear in that case, plus log it.  And this is why we always want the log files.

**Comment by VAKazakov** [comment] 2020-10-14 16:07
One of my pilots appear to have that problem as well, so here is info
Version: 4.1.3
OS: Win 10 x64
OS Locale: Russian
Logs:
[EDMarketConnector.log](https://github.com/EDCD/EDMarketConnector/files/5379470/EDMarketConnector.log)
[EDMarketConnector-debug.log](https://github.com/EDCD/EDMarketConnector/files/5379471/EDMarketConnector-debug.log)
Ping me in #edmc, if some additional info needed

**Comment by Athanasius** [comment] 2020-10-15 10:56
For completeness, as discussed on Discord.

This turned out to be someone running under Windows 10, build 17134 (Version 1803), but having set EDMarketConnector.exe to run under Windows 7 compatibilty for some reason.  We've now implemented an extra Windows version check before even attempting to set UTF-8 encoding, as in this case no exception was even thrown.

Fix released in 4.1.4

**Closed by Athanasius** 2020-10-15 10:56 UTC
Labels: bug, unconfirmed

**Comment by TonyFlury** [comment] 2020-10-15 23:02
Just A note - my issue wasn't running under compatibility mode. My issue was resolved by a restart, so I am guessing it was the zombie process issue.
Thanks to the team for a great response.
